prgrms-aibe-devcourse/AIBE1-Project2-Team07-Frontend

public/javascripts/user-mypage.js, public/stylesheets/user-mypage.css, public/user-mypage.html
---
사용자 마이페이지 디자인
- 기본 프로필 정보 관리
- 내가 작성한 글, 후기, 댓글 조회
- 글쓰기 버튼을 검색창으로 변경
---
- Resolves: #6 
---
1. 기본 프로필 정보 관리
2. 내가 작성한 글
3. 내가 작성한 후기
4. 내가 좋아요한 글
5. 내가 작성한 댓글
---
TODO: 구독 서비스 해야함
TODO: 프로필에 검색창 제외하기
---
=> 사용자 마이페이지 디자인 완료

public/common.html
---
- 네비게이션 바 링크 연결
- 커뮤니티: `/community`
- 훈련사: `/trainer`
- 내 프로필: `/profile`
---
- Resolves: #11 
---
- express router 코드는 직접 추가하셔야 합니다!
---
=> refactor: 네비게이션 바 링크 수정

public/javascripts/trainer-mypage.js, public/stylesheets/trainer-mypage.css, public/stylesheets/user-mypage.css, public/trainer-mypage.html
---
훈련사 마이페이지 완료 + user-mypage.css 일부 수정
---
- Resolves: #9 
---
- 훈련사 마이페이지
- 훈련사 내가쓴글
- 훈련사 내가 받은 후기
- 훈련사 좋아요한 글
- 훈련사 상담 신청 내역
---
=> 훈련사 마이페이지 완료

public/javascripts/trainer-mypage-modal.js, public/javascripts/trainer-mypage.js, public/javascripts/trainer-profile-modal.js, public/stylesheets/trainer-mypage-modal.css, public/stylesheets/trainer-profile-modal.css, public/trainer-mypage.html, public/trainer-profile.html
---
훈련사 상담 상세/수락/거절, 신청 모달 수정 완료
---
- Resolves: #18 
---
- 훈련사 상담 상세/수락/거절
- 신청 모달 수정
- 신청대기인것만 수락하기, 거절하기 버튼 뜨도록 변경
---
=> 훈련사 상담 상세/수락/거절, 신청 모달 수정 완료

.dockerignore, .github/workflows/build_image.yml, .github/workflows/main.yml, Dockerfile
---
- 배포를 위한 ci 관련 파일 추가
---
- Resolves: #22 
---
- 도커 이미지를 이용해서 keyeb 배포 진행
---
=> ci: 워크플로우 관련 파일 추가

public/javascripts/trainer-mypage.js, public/javascripts/user-mypage-modal.js, public/javascripts/user-mypage.js, public/stylesheets/user-mypage-modal.css, public/user-mypage.html
---
- 훈련사 업뎃 모달 기능
- 훈련사 프로필 소속 제외, 디자인 수정
---
- Resolves: #28 
---
- 훈련사 업뎃 모달 기능
- 훈련사 프로필 소속 제외, 디자인 수정
---
=> 훈련사 등업 모달 기능, 훈련사 프로필 재정의

public/javascripts/certification-modal.js, public/javascripts/trainer-mypage.js, public/javascripts/trainer-profile-modal.js, public/stylesheets/certification-modal.css, public/trainer-mypage.html, public/trainer-profile.html, public/user-mypage.html
---
- 사용자 프로필 검색창 hidden 말고 없애는 부분 개선
- 검색 안되는 부분 해결
- 사진첨부 기능 추가
---
- Resolves: #17 
---
- 사용자 프로필 검색창 hidden 말고 없애는 부분 개선
---
=> 사용자, 훈련사 마이페이지 리펙토링 완료

public/javascripts/trainer-edit-modal.js, public/javascripts/trainer-profile.js, public/stylesheets/trainer-edit-modal.css, public/stylesheets/trainer-profile-modal.css, public/stylesheets/trainer-profile.css, public/trainer-profile.html
---
- 훈련사 프로필 수정 버튼(훈련사 본인이 접속했을 때만 뜨도록)
- 훈련사 프로필 수정 모달 폼
---
- Resolves: #30 
---
- 훈련사 프로필 수정 버튼
- 훈련사 프로필 수정 모달 폼
---
=> 훈련사 프로필 수정 기능 완료

public/javascripts/trainer-list.js, public/javascripts/trainer-profile.js, public/trainer-list.html, public/trainer-profile.html
---
- 방문상담, 영상상담 분류/list에서의 연동까지
---
- Resolves: #36 
---
- list에서 영상, 방문 버튼중 하나를 누르면 해당하는 라디오 버튼이 자동으로 눌러지도록 하는 기능
- 교육문의 폼
---
=> 방문상담, 영상상담 분류 완료

public/javascripts/user-advice.js, public/javascripts/user-mypage.js, public/stylesheets/user-advice.css, public/user-mypage.html
---
- 사용자 리뷰 탭 추가, 상세보기, 리뷰작성, 작성한 리뷰 보기
---
- Resolves: #35 
---
- 사용자 리뷰 탭 추가
- 상세보기 모달
- 리뷰작성 모달
- 작성한 리뷰 보기 모달
---
=> 사용자 리뷰 탭 추가

public/community-post.html, public/community-write.html, public/community.html, public/trainer-list.html, public/trainer-mypage.html, public/trainer-profile.html, public/user-mypage.html
---
- common.js 추가 안한부분 추가
- 경로 몇가지 수정
---
=> 경로, common 수정

public/login.html, routes/auth.js
---
- 쿠키 로그인 방식에서 쿼리 파라미터로 변경
---
=> refactor: 로그인 관련 코드 리팩터링

public/login.html
---
-
---
- Resolves: #43 
---
-
---
-
---
=> refactor: 로그인 관련 코드 리팩터링 #43

package-lock.json, package.json, public/login.html, routes/auth.js, routes/trainers.js
=> feat: 유저 정보 로컬스토리지에 추가

public/javascripts/advice-request-modal.js, public/trainer-profile.html
---
- 파일오류 해결 + 매칭 연결 완료(파일전송제외)
---
- Resolves: #46 
---
=> 파일오류 해결 + 매칭 연결 완료(파일전송제외)

public/javascripts/trainer-list.js, public/javascripts/trainer-mypage.js, public/javascripts/trainer-profile.js, public/trainer-mypage.html, public/trainer-profile.html, routes/trainers.js
---
feat: 훈련사 프로필(백엔드 서버와 연결)
---
---
-
---
-
---
=> feat: 훈련사 프로필(백엔드 서버와 연결)

public/javascripts/home.js, public/login.html
=> refactor: 메인 페이지 백엔드 연동 코드 개선

public/javascripts/trainer-list.js, routes/auth.js, routes/profile.js
=> refactor: 프로필 관련 라우터 개선

public/javascripts/user-advice.js, public/javascripts/user-mypage.js, public/user-mypage.html
=> 사용자 마이페이지 일부 연동

public/cert.html, public/javascripts/cert.js, public/javascripts/user-mypage.js
=> 상담상세보기 사진추가 + 코드정리

app.js, middlewares/proxyMiddleware.js, public/javascripts/advice-request-modal.js, public/javascripts/community-edit.js, public/javascripts/community-post.js, public/javascripts/community-write.js, public/javascripts/community.js, public/javascripts/home.js, public/javascripts/trainer-list.js, public/javascripts/trainer-mypage-modal.js, public/javascripts/trainer-mypage.js, public/javascripts/trainer-profile.js, routes/auth.js
---
- express 프록시 관련 코드들 url 수정
---
---
-
---
-
---
=> refactor: express 프록시 관련 코드 수정

public/javascripts/community-edit.js, public/javascripts/user-mypage.js
=> fix: express 프록시 관련 코드 버그 수정

public/javascripts/common.js, public/javascripts/trainer-edit-modal.js, public/javascripts/trainer-list.js, public/javascripts/trainer-profile.js, public/stylesheets/home.css, public/stylesheets/trainer-list.css, public/trainer-list.html, public/trainer-profile.html
---
- 트레이너 프로필 업데이트 관련 백엔드 연동 추가
---
---
-
---
- 트레이너 이미지 업로드 관련 버그 수정 필요
---
=> refactor: 프로필 업데이트 개선

public/home.html
---
- llm 프롬프트 가이드 박스 수정
---
---
-
---
-
---
=> refactor: llm 프롬프트 가이드 아이템 수정
